# Generated by Django 4.2 on 2026-01-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0015_alter_transaksi_alamat_pengiriman'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='nama_bank',
            field=models.CharField(max_length=100, null=True, verbose_name='Nama Bank'),
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='nomor_rekening',
            field=models.CharField(max_length=50, null=True, verbose_name='Nomor Rekening'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='bukti_refund',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_refund/', verbose_name='Bukti Refund'),
        ),
    ]
