# Generated by Django 4.2 on 2026-01-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0016_pelanggan_nama_bank_pelanggan_nomor_rekening_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='catatan_pembatalan',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan Pembatalan'),
        ),
    ]
